/*
 * Copyright (c) 2017, GoMint, BlackyPaw and geNAZt
 *
 * This code is licensed under the BSD license found in the
 * LICENSE file in the root directory of this source tree.
 */

package io.gomint.server.util;

/**
 * @author generated
 * @version 2.0
 */
public class EnumConverterFromSoundMagicNumbers implements EnumConverter {

    public Enum convert( Enum value ) {
        int id = value.ordinal();
        switch ( id ) {
            case 0:
                return io.gomint.server.world.SoundMagicNumbers.ITEM_USE_ON;
            case 1:
                return io.gomint.server.world.SoundMagicNumbers.HIT;
            case 2:
                return io.gomint.server.world.SoundMagicNumbers.STEP;
            case 3:
                return io.gomint.server.world.SoundMagicNumbers.FLY;
            case 4:
                return io.gomint.server.world.SoundMagicNumbers.JUMP;
            case 5:
                return io.gomint.server.world.SoundMagicNumbers.BREAK;
            case 6:
                return io.gomint.server.world.SoundMagicNumbers.PLACE;
            case 7:
                return io.gomint.server.world.SoundMagicNumbers.HEAVY_STEP;
            case 8:
                return io.gomint.server.world.SoundMagicNumbers.GALLOP;
            case 9:
                return io.gomint.server.world.SoundMagicNumbers.FALL;
            case 10:
                return io.gomint.server.world.SoundMagicNumbers.AMBIENT;
            case 11:
                return io.gomint.server.world.SoundMagicNumbers.AMBIENT_BABY;
            case 12:
                return io.gomint.server.world.SoundMagicNumbers.AMBIENT_IN_WATER;
            case 13:
                return io.gomint.server.world.SoundMagicNumbers.BREATHE;
            case 14:
                return io.gomint.server.world.SoundMagicNumbers.DEATH;
            case 15:
                return io.gomint.server.world.SoundMagicNumbers.DEATH_IN_WATER;
            case 16:
                return io.gomint.server.world.SoundMagicNumbers.DEATH_TO_ZOMBIE;
            case 17:
                return io.gomint.server.world.SoundMagicNumbers.HURT;
            case 18:
                return io.gomint.server.world.SoundMagicNumbers.HURT_IN_WATER;
            case 19:
                return io.gomint.server.world.SoundMagicNumbers.MAD;
            case 20:
                return io.gomint.server.world.SoundMagicNumbers.BOOST;
            case 21:
                return io.gomint.server.world.SoundMagicNumbers.BOW;
            case 22:
                return io.gomint.server.world.SoundMagicNumbers.SQUISH_BIG;
            case 23:
                return io.gomint.server.world.SoundMagicNumbers.SQUISH_SMALL;
            case 24:
                return io.gomint.server.world.SoundMagicNumbers.FALL_BIG;
            case 25:
                return io.gomint.server.world.SoundMagicNumbers.FALL_SMALL;
            case 26:
                return io.gomint.server.world.SoundMagicNumbers.SPLASH;
            case 27:
                return io.gomint.server.world.SoundMagicNumbers.FIZZ;
            case 28:
                return io.gomint.server.world.SoundMagicNumbers.FLAP;
            case 29:
                return io.gomint.server.world.SoundMagicNumbers.SWIM;
            case 30:
                return io.gomint.server.world.SoundMagicNumbers.DRINK;
            case 31:
                return io.gomint.server.world.SoundMagicNumbers.EAT;
            case 32:
                return io.gomint.server.world.SoundMagicNumbers.TAKEOFF;
            case 33:
                return io.gomint.server.world.SoundMagicNumbers.SHAKE;
            case 34:
                return io.gomint.server.world.SoundMagicNumbers.PLOP;
            case 35:
                return io.gomint.server.world.SoundMagicNumbers.LAND;
            case 36:
                return io.gomint.server.world.SoundMagicNumbers.SADDLE;
            case 37:
                return io.gomint.server.world.SoundMagicNumbers.ARMOR;
            case 38:
                return io.gomint.server.world.SoundMagicNumbers.ADD_CHEST;
            case 39:
                return io.gomint.server.world.SoundMagicNumbers.THROW;
            case 40:
                return io.gomint.server.world.SoundMagicNumbers.ATTACK;
            case 41:
                return io.gomint.server.world.SoundMagicNumbers.ATTACK_NODAMAGE;
            case 42:
                return io.gomint.server.world.SoundMagicNumbers.ATTACK_STRONG;
            case 43:
                return io.gomint.server.world.SoundMagicNumbers.WARN;
            case 44:
                return io.gomint.server.world.SoundMagicNumbers.SHEAR;
            case 45:
                return io.gomint.server.world.SoundMagicNumbers.MILK;
            case 46:
                return io.gomint.server.world.SoundMagicNumbers.THUNDER;
            case 47:
                return io.gomint.server.world.SoundMagicNumbers.EXPLODE;
            case 48:
                return io.gomint.server.world.SoundMagicNumbers.FIRE;
            case 49:
                return io.gomint.server.world.SoundMagicNumbers.IGNITE;
            case 50:
                return io.gomint.server.world.SoundMagicNumbers.FUSE;
            case 51:
                return io.gomint.server.world.SoundMagicNumbers.STARE;
            case 52:
                return io.gomint.server.world.SoundMagicNumbers.SPAWN;
            case 53:
                return io.gomint.server.world.SoundMagicNumbers.SHOOT;
            case 54:
                return io.gomint.server.world.SoundMagicNumbers.BREAK_BLOCK;
            case 55:
                return io.gomint.server.world.SoundMagicNumbers.LAUNCH;
            case 56:
                return io.gomint.server.world.SoundMagicNumbers.BLAST;
            case 57:
                return io.gomint.server.world.SoundMagicNumbers.LARGE_BLAST;
            case 58:
                return io.gomint.server.world.SoundMagicNumbers.TWINKLE;
            case 59:
                return io.gomint.server.world.SoundMagicNumbers.REMEDY;
            case 60:
                return io.gomint.server.world.SoundMagicNumbers.UNFECT;
            case 61:
                return io.gomint.server.world.SoundMagicNumbers.LEVELUP;
            case 62:
                return io.gomint.server.world.SoundMagicNumbers.BOW_HIT;
            case 63:
                return io.gomint.server.world.SoundMagicNumbers.BULLET_HIT;
            case 64:
                return io.gomint.server.world.SoundMagicNumbers.EXTINGUISH_FIRE;
            case 65:
                return io.gomint.server.world.SoundMagicNumbers.ITEM_FIZZ;
            case 66:
                return io.gomint.server.world.SoundMagicNumbers.CHEST_OPEN;
            case 67:
                return io.gomint.server.world.SoundMagicNumbers.CHEST_CLOSED;
            case 68:
                return io.gomint.server.world.SoundMagicNumbers.SHULKERBOX_OPEN;
            case 69:
                return io.gomint.server.world.SoundMagicNumbers.SHULKERBOX_CLOSED;
            case 70:
                return io.gomint.server.world.SoundMagicNumbers.POWER_ON;
            case 71:
                return io.gomint.server.world.SoundMagicNumbers.POWER_OFF;
            case 72:
                return io.gomint.server.world.SoundMagicNumbers.ATTACH;
            case 73:
                return io.gomint.server.world.SoundMagicNumbers.DETACH;
            case 74:
                return io.gomint.server.world.SoundMagicNumbers.DENY;
            case 75:
                return io.gomint.server.world.SoundMagicNumbers.TRIPOD;
            case 76:
                return io.gomint.server.world.SoundMagicNumbers.POP;
            case 77:
                return io.gomint.server.world.SoundMagicNumbers.DROP_SLOT;
            case 78:
                return io.gomint.server.world.SoundMagicNumbers.NOTE;
            case 79:
                return io.gomint.server.world.SoundMagicNumbers.THORNS;
            case 80:
                return io.gomint.server.world.SoundMagicNumbers.PISTON_IN;
            case 81:
                return io.gomint.server.world.SoundMagicNumbers.PISTON_OUT;
            case 82:
                return io.gomint.server.world.SoundMagicNumbers.PORTAL;
            case 83:
                return io.gomint.server.world.SoundMagicNumbers.WATER;
            case 84:
                return io.gomint.server.world.SoundMagicNumbers.LAVA_POP;
            case 85:
                return io.gomint.server.world.SoundMagicNumbers.LAVA;
            case 86:
                return io.gomint.server.world.SoundMagicNumbers.BURP;
            case 87:
                return io.gomint.server.world.SoundMagicNumbers.BUCKET_FILL_WATER;
            case 88:
                return io.gomint.server.world.SoundMagicNumbers.BUCKET_FILL_LAVA;
            case 89:
                return io.gomint.server.world.SoundMagicNumbers.BUCKET_EMPTY_WATER;
            case 90:
                return io.gomint.server.world.SoundMagicNumbers.BUCKET_EMPTY_LAVA;
            case 91:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_13;
            case 92:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_CAT;
            case 93:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_BLOCKS;
            case 94:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_CHIRP;
            case 95:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_FAR;
            case 96:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_MALL;
            case 97:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_MELLOHI;
            case 98:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_STAL;
            case 99:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_STRAD;
            case 100:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_WARD;
            case 101:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_11;
            case 102:
                return io.gomint.server.world.SoundMagicNumbers.RECORD_WAIT;
            case 103:
                return io.gomint.server.world.SoundMagicNumbers.GUARDIAN_FLOP;
            case 104:
                return io.gomint.server.world.SoundMagicNumbers.ELDERGUARDIAN_CURSE;
            case 105:
                return io.gomint.server.world.SoundMagicNumbers.MOB_WARNING;
            case 106:
                return io.gomint.server.world.SoundMagicNumbers.MOB_WARNING_BABY;
            case 107:
                return io.gomint.server.world.SoundMagicNumbers.TELEPORT;
            case 108:
                return io.gomint.server.world.SoundMagicNumbers.SHULKER_OPEN;
            case 109:
                return io.gomint.server.world.SoundMagicNumbers.SHULKER_CLOSE;
            case 110:
                return io.gomint.server.world.SoundMagicNumbers.HAGGLE;
            case 111:
                return io.gomint.server.world.SoundMagicNumbers.HAGGLE_YES;
            case 112:
                return io.gomint.server.world.SoundMagicNumbers.HAGGLE_NO;
            case 113:
                return io.gomint.server.world.SoundMagicNumbers.HAGGLE_IDLE;
            case 114:
                return io.gomint.server.world.SoundMagicNumbers.CHORUSGROW;
            case 115:
                return io.gomint.server.world.SoundMagicNumbers.CHORUSDEATH;
            case 116:
                return io.gomint.server.world.SoundMagicNumbers.GLASS;
            case 117:
                return io.gomint.server.world.SoundMagicNumbers.CAST_SPELL;
            case 118:
                return io.gomint.server.world.SoundMagicNumbers.PREPARE_ATTACK;
            case 119:
                return io.gomint.server.world.SoundMagicNumbers.PREPARE_SUMMON;
            case 120:
                return io.gomint.server.world.SoundMagicNumbers.PREPARE_WOLOLO;
            case 121:
                return io.gomint.server.world.SoundMagicNumbers.FANG;
            case 122:
                return io.gomint.server.world.SoundMagicNumbers.CHARGE;
            case 123:
                return io.gomint.server.world.SoundMagicNumbers.CAMERA_TAKE_PICTURE;
            case 124:
                return io.gomint.server.world.SoundMagicNumbers.LEASHKNOT_PLACE;
            case 125:
                return io.gomint.server.world.SoundMagicNumbers.LEASHKNOT_BREAK;
            case 126:
                return io.gomint.server.world.SoundMagicNumbers.GROWL;
            case 127:
                return io.gomint.server.world.SoundMagicNumbers.WHINE;
            case 128:
                return io.gomint.server.world.SoundMagicNumbers.PANT;
            case 129:
                return io.gomint.server.world.SoundMagicNumbers.PURR;
            case 130:
                return io.gomint.server.world.SoundMagicNumbers.PURREOW;
            case 131:
                return io.gomint.server.world.SoundMagicNumbers.DEATH_MIN_VOLUME;
            case 132:
                return io.gomint.server.world.SoundMagicNumbers.DEATH_MID_VOLUME;
            case 133:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_BLAZE;
            case 134:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_CAVE_SPIDER;
            case 135:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_CREEPER;
            case 136:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_ELDER_GUARDIAN;
            case 137:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_ENDER_DRAGON;
            case 138:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_ENDERMAN;
            case 139:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_EVOCATION_ILLAGER;
            case 140:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_GHAST;
            case 141:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_HUSK;
            case 142:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_ILLUSION_ILLAGER;
            case 143:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_MAGMA_CUBE;
            case 144:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_POLAR_BEAR;
            case 145:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_SHULKER;
            case 146:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_SILVERFISH;
            case 147:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_SKELETON;
            case 148:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_SLIME;
            case 149:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_SPIDER;
            case 150:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_STRAY;
            case 151:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_VEX;
            case 152:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_VINDICATION_ILLAGER;
            case 153:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_WITCH;
            case 154:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_WITHER;
            case 155:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_WITHER_SKELETON;
            case 156:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_WOLF;
            case 157:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_ZOMBIE;
            case 158:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_ZOMBIE_PIGMAN;
            case 159:
                return io.gomint.server.world.SoundMagicNumbers.IMITATE_ZOMBIE_VILLAGER;
            case 160:
                return io.gomint.server.world.SoundMagicNumbers.BLOCK_END_PORTAL_FRAME_FILL;
            case 161:
                return io.gomint.server.world.SoundMagicNumbers.BLOCK_END_PORTAL_SPAWN;
            case 162:
                return io.gomint.server.world.SoundMagicNumbers.RANDOM_ANVIL_USE;
            case 163:
                return io.gomint.server.world.SoundMagicNumbers.BOTTLE_DRAGONBREATH;
        }

        return null;
    }

}
