package io.gomint.server.world;

import lombok.Getter;

/**
 * @author geNAZt
 * @version 1.0
 */
public enum SoundMagicNumbers {

    ITEM_USE_ON( 0 ),
    HIT( 1 ),
    STEP( 2 ),
    FLY( 3 ),
    JUMP( 4 ),
    BREAK( 5 ),
    PLACE( 6 ),
    HEAVY_STEP( 7 ),
    GALLOP( 8 ),
    FALL( 9 ),
    AMBIENT( 10 ),
    AMBIENT_BABY( 11 ),
    AMBIENT_IN_WATER( 12 ),
    BREATHE( 13 ),
    DEATH( 14 ),
    DEATH_IN_WATER( 15 ),
    DEATH_TO_ZOMBIE( 16 ),
    HURT( 17 ),
    HURT_IN_WATER( 18 ),
    MAD( 19 ),
    BOOST( 20 ),
    BOW( 21 ),
    SQUISH_BIG( 22 ),
    SQUISH_SMALL( 23 ),
    FALL_BIG( 24 ),
    FALL_SMALL( 25 ),
    SPLASH( 26 ),
    FIZZ( 27 ),
    FLAP( 28 ),
    SWIM( 29 ),
    DRINK( 30 ),
    EAT( 31 ),
    TAKEOFF( 32 ),
    SHAKE( 33 ),
    PLOP( 34 ),
    LAND( 35 ),
    SADDLE( 36 ),
    ARMOR( 37 ),
    ADD_CHEST( 38 ),
    THROW( 39 ),
    ATTACK( 40 ),
    ATTACK_NODAMAGE( 41 ),
    WARN( 42 ),
    SHEAR( 43 ),
    MILK( 44 ),
    THUNDER( 45 ),
    EXPLODE( 46 ),
    FIRE( 47 ),
    IGNITE( 48 ),
    FUSE( 49 ),
    STARE( 50 ),
    SPAWN( 51 ),
    SHOOT( 52 ),
    BREAK_BLOCK( 53 ),
    LAUNCH( 54 ),
    BLAST( 55 ),
    LARGE_BLAST( 56 ),
    TWINKLE( 57 ),
    REMEDY( 58 ),
    UNFECT( 59 ),
    LEVELUP( 60 ),
    BOW_HIT( 61 ),
    BULLET_HIT( 62 ),
    EXTINGUISH_FIRE( 63 ),
    ITEM_FIZZ( 64 ),
    CHEST_OPEN( 65 ),
    CHEST_CLOSED( 66 ),
    SHULKERBOX_OPEN( 67 ),
    SHULKERBOX_CLOSED( 68 ),
    POWER_ON( 69 ),
    POWER_OFF( 70 ),
    ATTACH( 71 ),
    DETACH( 72 ),
    DENY( 73 ),
    TRIPOD( 74 ),
    POP( 75 ),
    DROP_SLOT( 76 ),
    NOTE( 77 ),
    THORNS( 78 ),
    PISTON_IN( 79 ),
    PISTON_OUT( 80 ),
    PORTAL( 81 ),
    WATER( 82 ),
    LAVA_POP( 83 ),
    LAVA( 84 ),
    BURP( 85 ),
    BUCKET_FILL_WATER( 86 ),
    BUCKET_FILL_LAVA( 87 ),
    BUCKET_EMPTY_WATER( 88 ),
    BUCKET_EMPTY_LAVA( 89 ),
    RECORD_13( 90 ),
    RECORD_CAT( 91 ),
    RECORD_BLOCKS( 92 ),
    RECORD_CHIRP( 93 ),
    RECORD_FAR( 94 ),
    RECORD_MALL( 95 ),
    RECORD_MELLOHI( 96 ),
    RECORD_STAL( 97 ),
    RECORD_STRAD( 98 ),
    RECORD_WARD( 99 ),
    RECORD_11( 100 ),
    RECORD_WAIT( 101 ),
    GUARDIAN_FLOP( 103 ),
    ELDERGUARDIAN_CURSE( 104 ),
    MOB_WARNING( 105 ),
    MOB_WARNING_BABY( 106 ),
    TELEPORT( 107 ),
    SHULKER_OPEN( 108 ),
    SHULKER_CLOSE( 109 ),
    HAGGLE( 110 ),
    HAGGLE_YES( 111 ),
    HAGGLE_NO( 112 ),
    HAGGLE_IDLE( 113 ),
    CHORUSGROW( 114 ),
    CHORUSDEATH( 115 ),
    GLASS( 116 ),
    CAST_SPELL( 117 ),
    PREPARE_ATTACK( 118 ),
    PREPARE_SUMMON( 119 ),
    PREPARE_WOLOLO( 120 ),
    FANG( 121 ),
    CHARGE( 122 ),
    CAMERA_TAKE_PICTURE( 123 ),
    LEASHKNOT_PLACE( 124 ),
    LEASHKNOT_BREAK( 125 ),
    GROWL( 126 ),
    WHINE( 127 ),
    PANT( 128 ),
    PURR( 129 ),
    PURREOW( 130 ),
    DEATH_MIN_VOLUME( 131 ),
    DEATH_MID_VOLUME( 132 ),
    IMITATE_BLAZE( 133 ),
    IMITATE_CAVE_SPIDER( 134 ),
    IMITATE_CREEPER( 135 ),
    IMITATE_ELDER_GUARDIAN( 136 ),
    IMITATE_ENDER_DRAGON( 137 ),
    IMITATE_ENDERMAN( 138 ),
    IMITATE_EVOCATION_ILLAGER( 140 ),
    IMITATE_GHAST( 141 ),
    IMITATE_HUSK( 142 ),
    IMITATE_ILLUSION_ILLAGER( 143 ),
    IMITATE_MAGMA_CUBE( 144 ),
    IMITATE_POLAR_BEAR( 145 ),
    IMITATE_SHULKER( 146 ),
    IMITATE_SILVERFISH( 147 ),
    IMITATE_SKELETON( 148 ),
    IMITATE_SLIME( 149 ),
    IMITATE_SPIDER( 150 ),
    IMITATE_STRAY( 151 ),
    IMITATE_VEX( 152 ),
    IMITATE_VINDICATION_ILLAGER( 153 ),
    IMITATE_WITCH( 154 ),
    IMITATE_WITHER( 155 ),
    IMITATE_WITHER_SKELETON( 156 ),
    IMITATE_WOLF( 157 ),
    IMITATE_ZOMBIE( 158 ),
    IMITATE_ZOMBIE_PIGMAN( 159 ),
    IMITATE_ZOMBIE_VILLAGER( 160 ),
    DEFAULT( 161 ),
    UNDEFINED( 162 );

    @Getter
    private final byte soundId;

    SoundMagicNumbers( int soundId ) {
        this.soundId = (byte) soundId;
    }

    public static SoundMagicNumbers valueOf( byte id ) {
        for ( SoundMagicNumbers soundMagicNumbers : values() ) {
            if ( soundMagicNumbers.soundId == id ) {
                return soundMagicNumbers;
            }
        }

        return null;
    }

}
