package io.gomint.server.world;

import lombok.Getter;

/**
 * @author geNAZt
 * @version 1.0
 */
public enum SoundMagicNumbers {

    ITEM_USE_ON( 0 ),
    HIT( 1 ),
    STEP( 2 ),
    FLY( 3 ),
    JUMP( 4 ),
    BREAK( 5 ),
    PLACE( 6 ),
    HEAVY_STEP( 7 ),
    GALLOP( 8 ),
    FALL( 9 ),
    AMBIENT( 10 ),
    AMBIENT_BABY( 11 ),
    AMBIENT_IN_WATER( 12 ),
    BREATHE( 13 ),
    DEATH( 14 ),
    DEATH_IN_WATER( 15 ),
    DEATH_TO_ZOMBIE( 16 ),
    HURT( 17 ),
    HURT_IN_WATER( 18 ),
    MAD( 19 ),
    BOOST( 20 ),
    BOW( 21 ),
    SQUISH_BIG( 22 ),
    SQUISH_SMALL( 23 ),
    FALL_BIG( 24 ),
    FALL_SMALL( 25 ),
    SPLASH( 26 ),
    FIZZ( 27 ),
    FLAP( 28 ),
    SWIM( 29 ),
    DRINK( 30 ),
    EAT( 31 ),
    TAKEOFF( 32 ),
    SHAKE( 33 ),
    PLOP( 34 ),
    LAND( 35 ),
    SADDLE( 36 ),
    ARMOR( 37 ),
    ADD_CHEST( 38 ),
    THROW( 39 ),
    ATTACK( 40 ),
    ATTACK_NODAMAGE( 41 ),
    ATTACK_STRONG( 42 ),
    WARN( 43 ),
    SHEAR( 44 ),
    MILK( 45 ),
    THUNDER( 46 ),
    EXPLODE( 47 ),
    FIRE( 48 ),
    IGNITE( 49 ),
    FUSE( 50 ),
    STARE( 51 ),
    SPAWN( 52 ),
    SHOOT( 53 ),
    BREAK_BLOCK( 54 ),
    LAUNCH( 55 ),
    BLAST( 56 ),
    LARGE_BLAST( 57 ),
    TWINKLE( 58 ),
    REMEDY( 59 ),
    UNFECT( 60 ),
    LEVELUP( 61 ),
    BOW_HIT( 62 ),
    BULLET_HIT( 63 ),
    EXTINGUISH_FIRE( 64 ),
    ITEM_FIZZ( 65 ),
    CHEST_OPEN( 66 ),
    CHEST_CLOSED( 67 ),
    SHULKERBOX_OPEN( 68 ),
    SHULKERBOX_CLOSED( 69 ),
    POWER_ON( 70 ),
    POWER_OFF( 71 ),
    ATTACH( 72 ),
    DETACH( 73 ),
    DENY( 74 ),
    TRIPOD( 75 ),
    POP( 76 ),
    DROP_SLOT( 77 ),
    NOTE( 78 ),
    THORNS( 79 ),
    PISTON_IN( 80 ),
    PISTON_OUT( 81 ),
    PORTAL( 82 ),
    WATER( 83 ),
    LAVA_POP( 84 ),
    LAVA( 85 ),
    BURP( 86 ),
    BUCKET_FILL_WATER( 87 ),
    BUCKET_FILL_LAVA( 88 ),
    BUCKET_EMPTY_WATER( 89 ),
    BUCKET_EMPTY_LAVA( 90 ),
    RECORD_13( 91 ),
    RECORD_CAT( 92 ),
    RECORD_BLOCKS( 93 ),
    RECORD_CHIRP( 94 ),
    RECORD_FAR( 95 ),
    RECORD_MALL( 96 ),
    RECORD_MELLOHI( 97 ),
    RECORD_STAL( 98 ),
    RECORD_STRAD( 99 ),
    RECORD_WARD( 100 ),
    RECORD_11( 101 ),
    RECORD_WAIT( 102 ),
    GUARDIAN_FLOP( 104 ),
    ELDERGUARDIAN_CURSE( 105 ),
    MOB_WARNING( 106 ),
    MOB_WARNING_BABY( 107 ),
    TELEPORT( 108 ),
    SHULKER_OPEN( 109 ),
    SHULKER_CLOSE( 110 ),
    HAGGLE( 111 ),
    HAGGLE_YES( 112 ),
    HAGGLE_NO( 113 ),
    HAGGLE_IDLE( 114 ),
    CHORUSGROW( 115 ),
    CHORUSDEATH( 116 ),
    GLASS( 117 ),
    CAST_SPELL( 118 ),
    PREPARE_ATTACK( 119 ),
    PREPARE_SUMMON( 120 ),
    PREPARE_WOLOLO( 121 ),
    FANG( 122 ),
    CHARGE( 123 ),
    CAMERA_TAKE_PICTURE( 124 ),
    LEASHKNOT_PLACE( 125 ),
    LEASHKNOT_BREAK( 126 ),
    GROWL( 127 ),
    WHINE( 128 ),
    PANT( 129 ),
    PURR( 130 ),
    PURREOW( 131 ),
    DEATH_MIN_VOLUME( 132 ),
    DEATH_MID_VOLUME( 133 ),
    IMITATE_BLAZE( 134 ),
    IMITATE_CAVE_SPIDER( 135 ),
    IMITATE_CREEPER( 136 ),
    IMITATE_ELDER_GUARDIAN( 137 ),
    IMITATE_ENDER_DRAGON( 138 ),
    IMITATE_ENDERMAN( 139 ),
    IMITATE_EVOCATION_ILLAGER( 141 ),
    IMITATE_GHAST( 142 ),
    IMITATE_HUSK( 143 ),
    IMITATE_ILLUSION_ILLAGER( 144 ),
    IMITATE_MAGMA_CUBE( 145 ),
    IMITATE_POLAR_BEAR( 146 ),
    IMITATE_SHULKER( 147 ),
    IMITATE_SILVERFISH( 148 ),
    IMITATE_SKELETON( 149 ),
    IMITATE_SLIME( 150 ),
    IMITATE_SPIDER( 151 ),
    IMITATE_STRAY( 152 ),
    IMITATE_VEX( 153 ),
    IMITATE_VINDICATION_ILLAGER( 154 ),
    IMITATE_WITCH( 155 ),
    IMITATE_WITHER( 156 ),
    IMITATE_WITHER_SKELETON( 157 ),
    IMITATE_WOLF( 158 ),
    IMITATE_ZOMBIE( 159 ),
    IMITATE_ZOMBIE_PIGMAN( 160 ),
    IMITATE_ZOMBIE_VILLAGER( 161 ),
    BLOCK_END_PORTAL_FRAME_FILL( 162 ),
    BLOCK_END_PORTAL_SPAWN( 163 ),
    RANDOM_ANVIL_USE( 164 ),
    BOTTLE_DRAGONBREATH( 165 );

    @Getter
    private final byte soundId;

    SoundMagicNumbers( int soundId ) {
        this.soundId = (byte) soundId;
    }

    public static SoundMagicNumbers valueOf( byte id ) {
        for ( SoundMagicNumbers soundMagicNumbers : values() ) {
            if ( soundMagicNumbers.soundId == id ) {
                return soundMagicNumbers;
            }
        }

        return null;
    }

}
