/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_gomint_server_jni_hash_HashNative */

#ifndef _Included_io_gomint_server_jni_hash_HashNative
#define _Included_io_gomint_server_jni_hash_HashNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_gomint_server_jni_hash_HashNative
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_gomint_server_jni_hash_HashNative_init
  (JNIEnv *, jclass);

/*
 * Class:     io_gomint_server_jni_hash_HashNative
 * Method:    update
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_io_gomint_server_jni_hash_HashNative_update
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     io_gomint_server_jni_hash_HashNative
 * Method:    digest
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_gomint_server_jni_hash_HashNative_digest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_gomint_server_jni_hash_HashNative
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_gomint_server_jni_hash_HashNative_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
