/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_gomint_server_jni_zlib_ZLibNative */

#ifndef _Included_io_gomint_server_jni_zlib_ZLibNative
#define _Included_io_gomint_server_jni_zlib_ZLibNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_gomint_server_jni_zlib_ZLibNative
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_gomint_server_jni_zlib_ZLibNative_initFields
  (JNIEnv *, jclass);

/*
 * Class:     io_gomint_server_jni_zlib_ZLibNative
 * Method:    end
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_gomint_server_jni_zlib_ZLibNative_end
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     io_gomint_server_jni_zlib_ZLibNative
 * Method:    reset
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_gomint_server_jni_zlib_ZLibNative_reset
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     io_gomint_server_jni_zlib_ZLibNative
 * Method:    init
 * Signature: (ZI)J
 */
JNIEXPORT jlong JNICALL Java_io_gomint_server_jni_zlib_ZLibNative_init
  (JNIEnv *, jobject, jboolean, jint);

/*
 * Class:     io_gomint_server_jni_zlib_ZLibNative
 * Method:    process
 * Signature: (JJIJIZ)I
 */
JNIEXPORT jint JNICALL Java_io_gomint_server_jni_zlib_ZLibNative_process
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
