/*
 * Copyright (c) 2017, GoMint, BlackyPaw and geNAZt
 *
 * This code is licensed under the BSD license found in the
 * LICENSE file in the root directory of this source tree.
 */

package io.gomint.world;

/**
 * @author geNAZt
 * @version 1.0
 */
public enum Sound {

    ITEM_USE_ON,
    HIT,
    STEP,
    JUMP,
    BREAK,
    PLACE,
    HEAVY_STEP,
    GALLOP,
    FALL,
    AMBIENT,
    AMBIENT_BABY,
    AMBIENT_IN_WATER,
    BREATHE,
    DEATH,
    DEATH_IN_WATER,
    DEATH_TO_ZOMBIE,
    HURT,
    HURT_IN_WATER,
    MAD,
    BOOST,
    BOW,
    SQUISH_BIG,
    SQUISH_SMALL,
    FALL_BIG,
    FALL_SMALL,
    SPLASH,
    FIZZ,
    FLAP,
    SWIM,
    DRINK,
    EAT,
    TAKEOFF,
    SHAKE,
    PLOP,
    LAND,
    SADDLE,
    ARMOR,
    ADD_CHEST,
    THROW,
    ATTACK,
    ATTACK_NODAMAGE,
    WARN,
    SHEAR,
    MILK,
    THUNDER,
    EXPLODE,
    FIRE,
    IGNITE,
    FUSE,
    STARE,
    SPAWN,
    SHOOT,
    BREAK_BLOCK,
    REMEDY,
    UNFECT,
    LEVELUP,
    BOW_HIT,
    BULLET_HIT,
    EXTINGUISH_FIRE,
    ITEM_FIZZ,
    CHEST_OPEN,
    CHEST_CLOSED,
    POWER_ON,
    POWER_OFF,
    ATTACH,
    DETACH,
    DENY,
    TRIPOD,
    POP,
    DROP_SLOT,
    NOTE,
    THORNS,
    PISTON_IN,
    PISTON_OUT,
    PORTAL,
    WATER,
    LAVA_POP,
    LAVA,
    BURP,
    BUCKET_FILL_WATER,
    BUCKET_FILL_LAVA,
    BUCKET_EMPTY_WATER,
    BUCKET_EMPTY_LAVA,
    GUARDIAN_FLOP,
    ELDERGUARDIAN_CURSE,
    MOB_WARNING,
    MOB_WARNING_BABY,
    TELEPORT,
    SHULKER_OPEN,
    SHULKER_CLOSE,
    HAGGLE,
    HAGGLE_YES,
    HAGGLE_NO,
    HAGGLE_IDLE,
    DEFAULT,
    UNDEFINED

}
